#region BSD License
/*
 *
 * Original BSD 3-Clause License (https://github.com/ComponentFactory/Krypton/blob/master/LICENSE)
 *  © Component Factory Pty Ltd, 2006 - 2016, (Version 4.5.0.0) All rights reserved.
 *
 *  New BSD 3-Clause License (https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/LICENSE)
 *  Modifications by Peter Wagner (aka Wagnerp), Simon Coghlan (aka Smurf-IV), Giduac & Ahmed Abdelhameed et al. 2017 - 2025. All rights reserved.
 *
 */
#endregion

namespace Krypton.Toolkit;

public abstract class AbstractBaseColorScheme
{
    public abstract Color TextLabelControl { get; }
    public abstract Color TextButtonNormal { get; }
    public abstract Color TextButtonChecked { get; }
    public abstract Color ButtonNormalBorder { get; }
    public abstract Color ButtonNormalDefaultBorder { get; }
    public abstract Color ButtonNormalBack1 { get; }
    public abstract Color ButtonNormalBack2 { get; }
    public abstract Color ButtonNormalDefaultBack1 { get; }
    public abstract Color ButtonNormalDefaultBack2 { get; }
    public abstract Color ButtonNormalNavigatorBack1 { get; }
    public abstract Color ButtonNormalNavigatorBack2 { get; }
    public abstract Color PanelClient { get; }
    public abstract Color PanelAlternative { get; }
    public abstract Color ControlBorder { get; }
    public abstract Color SeparatorHighBorder1 { get; }
    public abstract Color SeparatorHighBorder2 { get; }
    public abstract Color HeaderPrimaryBack1 { get; }
    public abstract Color HeaderPrimaryBack2 { get; }
    public abstract Color HeaderSecondaryBack1 { get; }
    public abstract Color HeaderSecondaryBack2 { get; }
    public abstract Color HeaderText { get; }
    public abstract Color StatusStripText { get; }
    public abstract Color ButtonBorder { get; }
    public abstract Color SeparatorLight { get; }
    public abstract Color SeparatorDark { get; }
    public abstract Color GripLight { get; }
    public abstract Color GripDark { get; }
    public abstract Color ToolStripBack { get; }
    public abstract Color StatusStripLight { get; }
    public abstract Color StatusStripDark { get; }
    public abstract Color ImageMargin { get; }
    public abstract Color ToolStripBegin { get; }
    public abstract Color ToolStripMiddle { get; }
    public abstract Color ToolStripEnd { get; }
    public abstract Color OverflowBegin { get; }
    public abstract Color OverflowMiddle { get; }
    public abstract Color OverflowEnd { get; }
    public abstract Color ToolStripBorder { get; }
    public abstract Color FormBorderActive { get; }
    public abstract Color FormBorderInactive { get; }
    public abstract Color FormBorderActiveLight { get; }
    public abstract Color FormBorderActiveDark { get; }
    public abstract Color FormBorderInactiveLight { get; }
    public abstract Color FormBorderInactiveDark { get; }
    public abstract Color FormBorderHeaderActive { get; }
    public abstract Color FormBorderHeaderInactive { get; }
    public abstract Color FormBorderHeaderActive1 { get; }
    public abstract Color FormBorderHeaderActive2 { get; }
    public abstract Color FormBorderHeaderInactive1 { get; }
    public abstract Color FormBorderHeaderInactive2 { get; }
    public abstract Color FormHeaderShortActive { get; }
    public abstract Color FormHeaderShortInactive { get; }
    public abstract Color FormHeaderLongActive { get; }
    public abstract Color FormHeaderLongInactive { get; }
    public abstract Color FormButtonBorderTrack { get; }
    public abstract Color FormButtonBack1Track { get; }
    public abstract Color FormButtonBack2Track { get; }
    public abstract Color FormButtonBorderPressed { get; }
    public abstract Color FormButtonBack1Pressed { get; }
    public abstract Color FormButtonBack2Pressed { get; }
    public abstract Color TextButtonFormNormal { get; }
    public abstract Color TextButtonFormTracking { get; }
    public abstract Color TextButtonFormPressed { get; }
    public abstract Color LinkNotVisitedOverrideControl { get; }
    public abstract Color LinkVisitedOverrideControl { get; }
    public abstract Color LinkPressedOverrideControl { get; }
    public abstract Color LinkNotVisitedOverridePanel { get; }
    public abstract Color LinkVisitedOverridePanel { get; }
    public abstract Color LinkPressedOverridePanel { get; }
    public abstract Color TextLabelPanel { get; }
    public abstract Color RibbonTabTextNormal { get; }
    public abstract Color RibbonTabTextChecked { get; }
    public abstract Color RibbonTabSelected1 { get; }
    public abstract Color RibbonTabSelected2 { get; }
    public abstract Color RibbonTabSelected3 { get; }
    public abstract Color RibbonTabSelected4 { get; }
    public abstract Color RibbonTabSelected5 { get; }
    public abstract Color RibbonTabTracking1 { get; }
    public abstract Color RibbonTabTracking2 { get; }
    public abstract Color RibbonTabHighlight1 { get; }
    public abstract Color RibbonTabHighlight2 { get; }
    public abstract Color RibbonTabHighlight3 { get; }
    public abstract Color RibbonTabHighlight4 { get; }
    public abstract Color RibbonTabHighlight5 { get; }
    public abstract Color RibbonTabSeparatorColor { get; }
    public abstract Color RibbonGroupsArea1 { get; }
    public abstract Color RibbonGroupsArea2 { get; }
    public abstract Color RibbonGroupsArea3 { get; }
    public abstract Color RibbonGroupsArea4 { get; }
    public abstract Color RibbonGroupsArea5 { get; }
    public abstract Color RibbonGroupBorder1 { get; }
    public abstract Color RibbonGroupBorder2 { get; }
    public abstract Color RibbonGroupTitle1 { get; }
    public abstract Color RibbonGroupTitle2 { get; }
    public abstract Color RibbonGroupBorderContext1 { get; }
    public abstract Color RibbonGroupBorderContext2 { get; }
    public abstract Color RibbonGroupTitleContext1 { get; }
    public abstract Color RibbonGroupTitleContext2 { get; }
    public abstract Color RibbonGroupDialogDark { get; }
    public abstract Color RibbonGroupDialogLight { get; }
    public abstract Color RibbonGroupTitleTracking1 { get; }
    public abstract Color RibbonGroupTitleTracking2 { get; }
    public abstract Color RibbonMinimizeBarDark { get; }
    public abstract Color RibbonMinimizeBarLight { get; }
    public abstract Color RibbonGroupCollapsedBorder1 { get; }
    public abstract Color RibbonGroupCollapsedBorder2 { get; }
    public abstract Color RibbonGroupCollapsedBorder3 { get; }
    public abstract Color RibbonGroupCollapsedBorder4 { get; }
    public abstract Color RibbonGroupCollapsedBack1 { get; }
    public abstract Color RibbonGroupCollapsedBack2 { get; }
    public abstract Color RibbonGroupCollapsedBack3 { get; }
    public abstract Color RibbonGroupCollapsedBack4 { get; }
    public abstract Color RibbonGroupCollapsedBorderT1 { get; }
    public abstract Color RibbonGroupCollapsedBorderT2 { get; }
    public abstract Color RibbonGroupCollapsedBorderT3 { get; }
    public abstract Color RibbonGroupCollapsedBorderT4 { get; }
    public abstract Color RibbonGroupCollapsedBackT1 { get; }
    public abstract Color RibbonGroupCollapsedBackT2 { get; }
    public abstract Color RibbonGroupCollapsedBackT3 { get; }
    public abstract Color RibbonGroupCollapsedBackT4 { get; }
    public abstract Color RibbonGroupFrameBorder1 { get; }
    public abstract Color RibbonGroupFrameBorder2 { get; }
    public abstract Color RibbonGroupFrameInside1 { get; }
    public abstract Color RibbonGroupFrameInside2 { get; }
    public abstract Color RibbonGroupFrameInside3 { get; }
    public abstract Color RibbonGroupFrameInside4 { get; }
    public abstract Color RibbonGroupCollapsedText { get; }
    public abstract Color RibbonGroupButtonText { get; }
    public abstract Color AlternatePressedBack1 { get; }
    public abstract Color AlternatePressedBack2 { get; }
    public abstract Color AlternatePressedBorder1 { get; }
    public abstract Color AlternatePressedBorder2 { get; }
    public abstract Color FormButtonBack1Checked { get; }
    public abstract Color FormButtonBack2Checked { get; }
    public abstract Color FormButtonBorderCheck { get; }
    public abstract Color FormButtonBack1CheckTrack { get; }
    public abstract Color FormButtonBack2CheckTrack { get; }
    public abstract Color RibbonQATMini1 { get; }
    public abstract Color RibbonQATMini2 { get; }
    public abstract Color RibbonQATMini3 { get; }
    public abstract Color RibbonQATMini4 { get; }
    public abstract Color RibbonQATMini5 { get; }
    public abstract Color RibbonQATMini1I { get; }
    public abstract Color RibbonQATMini2I { get; }
    public abstract Color RibbonQATMini3I { get; }
    public abstract Color RibbonQATMini4I { get; }
    public abstract Color RibbonQATMini5I { get; }
    public abstract Color RibbonQATFullbar1 { get; }
    public abstract Color RibbonQATFullbar2 { get; }
    public abstract Color RibbonQATFullbar3 { get; }
    public abstract Color RibbonQATButtonDark { get; }
    public abstract Color RibbonQATButtonLight { get; }
    public abstract Color RibbonQATOverflow1 { get; }
    public abstract Color RibbonQATOverflow2 { get; }
    public abstract Color RibbonGroupSeparatorDark { get; }
    public abstract Color RibbonGroupSeparatorLight { get; }
    public abstract Color ButtonClusterButtonBack1 { get; }
    public abstract Color ButtonClusterButtonBack2 { get; }
    public abstract Color ButtonClusterButtonBorder1 { get; }
    public abstract Color ButtonClusterButtonBorder2 { get; }
    public abstract Color NavigatorMiniBackColor { get; }
    public abstract Color GridListNormal1 { get; }
    public abstract Color GridListNormal2 { get; }
    public abstract Color GridListPressed1 { get; }
    public abstract Color GridListPressed2 { get; }
    public abstract Color GridListSelected { get; }
    public abstract Color GridSheetColNormal1 { get; }
    public abstract Color GridSheetColNormal2 { get; }
    public abstract Color GridSheetColPressed1 { get; }
    public abstract Color GridSheetColPressed2 { get; }
    public abstract Color GridSheetColSelected1 { get; }
    public abstract Color GridSheetColSelected2 { get; }
    public abstract Color GridSheetRowNormal { get; }
    public abstract Color GridSheetRowPressed { get; }
    public abstract Color GridSheetRowSelected { get; }
    public abstract Color GridDataCellBorder { get; }
    public abstract Color GridDataCellSelected { get; }
    public abstract Color InputControlTextNormal { get; }
    public abstract Color InputControlTextDisabled { get; }
    public abstract Color InputControlBorderNormal { get; }
    public abstract Color InputControlBorderDisabled { get; }
    public abstract Color InputControlBackNormal { get; }
    public abstract Color InputControlBackDisabled { get; }
    public abstract Color InputControlBackInactive { get; }
    public abstract Color InputDropDownNormal1 { get; }
    public abstract Color InputDropDownNormal2 { get; }
    public abstract Color InputDropDownDisabled1 { get; }
    public abstract Color InputDropDownDisabled2 { get; }
    public abstract Color ContextMenuHeadingBack { get; }
    public abstract Color ContextMenuHeadingText { get; }
    public abstract Color ContextMenuImageColumn { get; }
    public abstract Color AppButtonBack1 { get; }
    public abstract Color AppButtonBack2 { get; }
    public abstract Color AppButtonBorder { get; }
    public abstract Color AppButtonOuter1 { get; }
    public abstract Color AppButtonOuter2 { get; }
    public abstract Color AppButtonOuter3 { get; }
    public abstract Color AppButtonInner1 { get; }
    public abstract Color AppButtonInner2 { get; }
    public abstract Color AppButtonMenuDocsBack { get; }
    public abstract Color AppButtonMenuDocsText { get; }
    public abstract Color SeparatorHighInternalBorder1 { get; }
    public abstract Color SeparatorHighInternalBorder2 { get; }
    public abstract Color RibbonGalleryBorder { get; }
    public abstract Color RibbonGalleryBackNormal { get; }
    public abstract Color RibbonGalleryBackTracking { get; }
    public abstract Color RibbonGalleryBack1 { get; }
    public abstract Color RibbonGalleryBack2 { get; }
    public abstract Color RibbonTabTracking3 { get; }
    public abstract Color RibbonTabTracking4 { get; }
    public abstract Color RibbonGroupBorder3 { get; }
    public abstract Color RibbonGroupBorder4 { get; }
    public abstract Color RibbonGroupBorder5 { get; }
    public abstract Color RibbonGroupTitleText { get; }
    public abstract Color RibbonDropArrowLight { get; }
    public abstract Color RibbonDropArrowDark { get; }
    public abstract Color HeaderDockInactiveBack1 { get; }
    public abstract Color HeaderDockInactiveBack2 { get; }
    public abstract Color ButtonNavigatorBorder { get; }
    public abstract Color ButtonNavigatorText { get; }
    public abstract Color ButtonNavigatorTrack1 { get; }
    public abstract Color ButtonNavigatorTrack2 { get; }
    public abstract Color ButtonNavigatorPressed1 { get; }
    public abstract Color ButtonNavigatorPressed2 { get; }
    public abstract Color ButtonNavigatorChecked1 { get; }
    public abstract Color ButtonNavigatorChecked2 { get; }
    public abstract Color ToolTipBottom { get; }
    public abstract Color MenuItemText { get; }
    public abstract Color MenuMarginGradientStart { get; }
    public abstract Color MenuMarginGradientMiddle { get; }
    public abstract Color MenuMarginGradientEnd { get; }
    public abstract Color DisabledMenuItemText { get; }
    public abstract Color MenuStripText { get; }
}
