//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", @"17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Office2010ControlBoxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", @"CA1811:AvoidUncalledPrivateCode")]
        internal Office2010ControlBoxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krypton.Toolkit.Resources.Office2010ControlBoxResources", typeof(Office2010ControlBoxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonCloseBlackNormal {
            get {
                object obj = ResourceManager.GetObject("2010ButtonCloseBlackNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonCloseHover {
            get {
                object obj = ResourceManager.GetObject("2010ButtonCloseHover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonCloseNormal {
            get {
                object obj = ResourceManager.GetObject("2010ButtonCloseNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMaxBlackNormal {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMaxBlackNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMaxNormal {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMaxNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIClose {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDICloseBlack {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDICloseBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIMax {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIMax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIMaxBlack {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIMaxBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIMin {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIMinBlack {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIMinBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIRestore {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMDIRestoreBlack {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMDIRestoreBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMin {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonMinBlack {
            get {
                object obj = ResourceManager.GetObject("2010ButtonMinBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonRestore {
            get {
                object obj = ResourceManager.GetObject("2010ButtonRestore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2010ButtonRestoreBlack {
            get {
                object obj = ResourceManager.GetObject("2010ButtonRestoreBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BackMaximiseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BackMaximiseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BackMaximiseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BackMaximiseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackCloseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackCloseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackCloseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackCloseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackCloseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackCloseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackCloseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackCloseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackCloseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackCloseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackCloseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackCloseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackClosePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackClosePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackClosePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackClosePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMaximiseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMaximiseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMaximiseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMaximiseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMaximiseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMaximiseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMaximiseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMaximiseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMaximisePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMaximisePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMaximisePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMaximisePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimiseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimiseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimiseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimiseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimiseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimiseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimiseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimiseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimiseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimiseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimiseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimiseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimisePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimisePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackMinimisePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackMinimisePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestoreDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestoreDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestoreDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestoreDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestoreHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestoreHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestoreHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestoreHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestoreNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestoreNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestoreNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestoreNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestorePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestorePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlackRestorePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlackRestorePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueCloseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueCloseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueCloseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueCloseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueCloseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueCloseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueCloseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueCloseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueCloseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueCloseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueCloseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueCloseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueClosePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueClosePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueClosePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueClosePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximiseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximiseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximiseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximiseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximiseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximiseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximiseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximiseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximiseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximiseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximiseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximiseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximisePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximisePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMaximisePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMaximisePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimiseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimiseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimiseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimiseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimiseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimiseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimiseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimiseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimiseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimiseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimiseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimiseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimisePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimisePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueMinimisePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueMinimisePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestoreDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestoreDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestoreDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestoreDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestoreHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestoreHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestoreHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestoreHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestoreNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestoreNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestoreNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestoreNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestorePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestorePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010BlueRestorePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010BlueRestorePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverCloseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverCloseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverCloseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverCloseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverCloseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverCloseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverCloseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverCloseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverCloseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverCloseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverCloseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverCloseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverClosePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverClosePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverClosePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverClosePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximiseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximiseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximiseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximiseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximiseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximiseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximiseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximiseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximiseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximiseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximiseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximiseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximisePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximisePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMaximisePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMaximisePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimiseDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimiseDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimiseDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimiseDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimiseHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimiseHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimiseHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimiseHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimiseNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimiseNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimiseNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimiseNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimisePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimisePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverMinimisePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverMinimisePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestoreDisabled_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestoreDisabled_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestoreDisabled_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestoreDisabled_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestoreHover_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestoreHover_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestoreHover_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestoreHover_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestoreNormal_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestoreNormal_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestoreNormal_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestoreNormal_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestorePressed_13_x_12 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestorePressed_13_x_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office2010SilverRestorePressed_25_x_23 {
            get {
                object obj = ResourceManager.GetObject("Office2010SilverRestorePressed_25_x_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
