# New BSD 3-Clause License (https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/LICENSE)
# Modifications by Peter Wagner (aka Wagnerp), Simon Coghlan (aka Smurf-IV), tobitege et al. 2025 - 2025. All rights reserved.

name: "💬 Other Issues"
description: Any other issues that do not fall into one of the current categories.
labels:
  - discussion
  - other
body:
  - type: textarea
    attributes:
      label: Describe the issue
      placeholder: "How do I..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please describe your issue
      placeholder: I need help with...
    validations:
      required: true