# New BSD 3-Clause License (https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/LICENSE)
# Modifications by Peter Wagner (aka Wagnerp), Simon Coghlan (aka Smurf-IV), tobitege et al. 2025 - 2025. All rights reserved.

name: "❓ Post a Question"
description: Got a question to ask? Use this template to share with us.
labels:
 - question
 
body:
  - type: textarea
    attributes:
      label: What do you want to ask?
      placeholder: "How do I..."
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Please describe your question
    validations:
      required: true