//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krypton.Toolkit.ResourceFiles.WindowsXPEmbedded {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WindowsXPEmbeddedImageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WindowsXPEmbeddedImageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krypton.Toolkit.ResourceFiles.WindowsXPEmbedded.WindowsXPEmbeddedImageResources", typeof(WindowsXPEmbeddedImageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BALLOONCLOSEBmp {
            get {
                object obj = ResourceManager.GetObject("BALLOONCLOSEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CAPTIONBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("CAPTIONBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkbox13Bmp {
            get {
                object obj = ResourceManager.GetObject("Checkbox13Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkbox16Bmp {
            get {
                object obj = ResourceManager.GetObject("Checkbox16Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Checkbox25 {
            get {
                object obj = ResourceManager.GetObject("Checkbox25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CHEVRONBmp {
            get {
                object obj = ResourceManager.GetObject("CHEVRONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLOSEBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("CLOSEBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closeglyph19Bmp {
            get {
                object obj = ResourceManager.GetObject("Closeglyph19Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closeglyph23Bmp {
            get {
                object obj = ResourceManager.GetObject("Closeglyph23Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closeglyph6Bmp {
            get {
                object obj = ResourceManager.GetObject("Closeglyph6Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Closeglyph9Bmp {
            get {
                object obj = ResourceManager.GetObject("Closeglyph9Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLOSEGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("CLOSEGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMBOBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("COMBOBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COMBOBUTTONGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("COMBOBUTTONGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARHEADERBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARHEADERBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARHEADERCLOSEBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARHEADERCLOSEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARHEADERPINBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARHEADERPINBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARTOOLBARBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARTOOLBARBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARTOOLBARBUTTONSBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARTOOLBARBUTTONSBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARTOOLBARBUTTONSSPLITBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARTOOLBARBUTTONSSPLITBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EXPLORERBARTOOLBARBUTTONSSPLITDROPDOWNBmp {
            get {
                object obj = ResourceManager.GetObject("EXPLORERBARTOOLBARBUTTONSSPLITDROPDOWNBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FIELDOUTLINEBLUEBmp {
            get {
                object obj = ResourceManager.GetObject("FIELDOUTLINEBLUEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrameBottom {
            get {
                object obj = ResourceManager.GetObject("FrameBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FRAMECAPTIONBmp {
            get {
                object obj = ResourceManager.GetObject("FRAMECAPTIONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FrameCaptionMin {
            get {
                object obj = ResourceManager.GetObject("FrameCaptionMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FRAMECAPTIONSIZINGBmp {
            get {
                object obj = ResourceManager.GetObject("FRAMECAPTIONSIZINGBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FRAMELEFTBmp {
            get {
                object obj = ResourceManager.GetObject("FRAMELEFTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FRAMEMAXIMIZEDBmp {
            get {
                object obj = ResourceManager.GetObject("FRAMEMAXIMIZEDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FRAMERIGHTBmp {
            get {
                object obj = ResourceManager.GetObject("FRAMERIGHTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GRIPPERBmp {
            get {
                object obj = ResourceManager.GetObject("GRIPPERBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GRIPPERVERTBmp {
            get {
                object obj = ResourceManager.GetObject("GRIPPERVERTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GROUPBOXBmp {
            get {
                object obj = ResourceManager.GetObject("GROUPBOXBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Helpglyph19Bmp {
            get {
                object obj = ResourceManager.GetObject("Helpglyph19Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Helpglyph23Bmp {
            get {
                object obj = ResourceManager.GetObject("Helpglyph23Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Helpglyph6Bmp {
            get {
                object obj = ResourceManager.GetObject("Helpglyph6Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Helpglyph9Bmp {
            get {
                object obj = ResourceManager.GetObject("Helpglyph9Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HELPGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("HELPGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IEPERSONALBARMENUBmp {
            get {
                object obj = ResourceManager.GetObject("IEPERSONALBARMENUBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ListViewHeader {
            get {
                object obj = ResourceManager.GetObject("ListViewHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LISTVIEWHEADERBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("LISTVIEWHEADERBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximizeglyph19Bmp {
            get {
                object obj = ResourceManager.GetObject("Maximizeglyph19Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximizeglyph23Bmp {
            get {
                object obj = ResourceManager.GetObject("Maximizeglyph23Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximizeglyph6Bmp {
            get {
                object obj = ResourceManager.GetObject("Maximizeglyph6Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximizeglyph9Bmp {
            get {
                object obj = ResourceManager.GetObject("Maximizeglyph9Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MAXIMIZEGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("MAXIMIZEGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDICAPTIONBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("MDICAPTIONBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDIGLYPHCLOSEBmp {
            get {
                object obj = ResourceManager.GetObject("MDIGLYPHCLOSEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDIGLYPHMINIMIZEBmp {
            get {
                object obj = ResourceManager.GetObject("MDIGLYPHMINIMIZEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MDIGLYPHRESTOREBmp {
            get {
                object obj = ResourceManager.GetObject("MDIGLYPHRESTOREBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimizeglyph19Bmp {
            get {
                object obj = ResourceManager.GetObject("Minimizeglyph19Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimizeglyph23Bmp {
            get {
                object obj = ResourceManager.GetObject("Minimizeglyph23Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimizeglyph6Bmp {
            get {
                object obj = ResourceManager.GetObject("Minimizeglyph6Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimizeglyph9Bmp {
            get {
                object obj = ResourceManager.GetObject("Minimizeglyph9Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MINIMIZEGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("MINIMIZEGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NORMALGROUPBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("NORMALGROUPBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NORMALGROUPCOLLAPSEBmp {
            get {
                object obj = ResourceManager.GetObject("NORMALGROUPCOLLAPSEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NORMALGROUPEXPANDBmp {
            get {
                object obj = ResourceManager.GetObject("NORMALGROUPEXPANDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NORMALGROUPHEADBmp {
            get {
                object obj = ResourceManager.GetObject("NORMALGROUPHEADBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PLACEBARBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("PLACEBARBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PLACEBARBUTTONSBmp {
            get {
                object obj = ResourceManager.GetObject("PLACEBARBUTTONSBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProgressChunk {
            get {
                object obj = ResourceManager.GetObject("ProgressChunk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROGRESSCHUNKVERTBmp {
            get {
                object obj = ResourceManager.GetObject("PROGRESSCHUNKVERTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProgressTrack {
            get {
                object obj = ResourceManager.GetObject("ProgressTrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROGRESSTRACKVERTBmp {
            get {
                object obj = ResourceManager.GetObject("PROGRESSTRACKVERTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radiobutton13Bmp {
            get {
                object obj = ResourceManager.GetObject("Radiobutton13Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radiobutton16Bmp {
            get {
                object obj = ResourceManager.GetObject("Radiobutton16Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RadioButton25 {
            get {
                object obj = ResourceManager.GetObject("RadioButton25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResizeGrip2 {
            get {
                object obj = ResourceManager.GetObject("ResizeGrip2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restoreglyph19Bmp {
            get {
                object obj = ResourceManager.GetObject("Restoreglyph19Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restoreglyph23Bmp {
            get {
                object obj = ResourceManager.GetObject("Restoreglyph23Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restoreglyph6Bmp {
            get {
                object obj = ResourceManager.GetObject("Restoreglyph6Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restoreglyph9Bmp {
            get {
                object obj = ResourceManager.GetObject("Restoreglyph9Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RESTOREGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("RESTOREGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollArrowGlyphs {
            get {
                object obj = ResourceManager.GetObject("ScrollArrowGlyphs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCROLLARROWGLYPHSSMALLBmp {
            get {
                object obj = ResourceManager.GetObject("SCROLLARROWGLYPHSSMALLBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollArrows {
            get {
                object obj = ResourceManager.GetObject("ScrollArrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCROLLSHAFTHORIZONTALBmp {
            get {
                object obj = ResourceManager.GetObject("SCROLLSHAFTHORIZONTALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCROLLSHAFTVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("SCROLLSHAFTVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCROLLTHUMBGRIPPERHORIZONTALBmp {
            get {
                object obj = ResourceManager.GetObject("SCROLLTHUMBGRIPPERHORIZONTALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SCROLLTHUMBGRIPPERVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("SCROLLTHUMBGRIPPERVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollThumbHorizontal {
            get {
                object obj = ResourceManager.GetObject("ScrollThumbHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScrollThumbVertical {
            get {
                object obj = ResourceManager.GetObject("ScrollThumbVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SEPARATORBmp {
            get {
                object obj = ResourceManager.GetObject("SEPARATORBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SEPARATORVERTBmp {
            get {
                object obj = ResourceManager.GetObject("SEPARATORVERTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SliderTrack {
            get {
                object obj = ResourceManager.GetObject("SliderTrack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALLCLOSEBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("SMALLCLOSEBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALLCLOSEGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("SMALLCLOSEGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALLFRAMECAPTIONBmp {
            get {
                object obj = ResourceManager.GetObject("SMALLFRAMECAPTIONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALLFRAMECAPTIONSIZINGBmp {
            get {
                object obj = ResourceManager.GetObject("SMALLFRAMECAPTIONSIZINGBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPECIALGROUPBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("SPECIALGROUPBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPECIALGROUPCOLLAPSEBmp {
            get {
                object obj = ResourceManager.GetObject("SPECIALGROUPCOLLAPSEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPECIALGROUPEXPANDBmp {
            get {
                object obj = ResourceManager.GetObject("SPECIALGROUPEXPANDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPECIALGROUPHEADBmp {
            get {
                object obj = ResourceManager.GetObject("SPECIALGROUPHEADBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpinButtonBackgroundDown {
            get {
                object obj = ResourceManager.GetObject("SpinButtonBackgroundDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPINBUTTONBACKGROUNDLEFTBmp {
            get {
                object obj = ResourceManager.GetObject("SPINBUTTONBACKGROUNDLEFTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPINBUTTONBACKGROUNDRIGHTBmp {
            get {
                object obj = ResourceManager.GetObject("SPINBUTTONBACKGROUNDRIGHTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpinButtonBackgroundUp {
            get {
                object obj = ResourceManager.GetObject("SpinButtonBackgroundUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPINDOWNGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("SPINDOWNGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPINLEFTGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("SPINLEFTGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPINRIGHTGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("SPINRIGHTGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPINUPGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("SPINUPGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("STARTBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTGROUPBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("STARTGROUPBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTGROUPNEWAPPBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("STARTGROUPNEWAPPBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTGROUPSEPERATORBmp {
            get {
                object obj = ResourceManager.GetObject("STARTGROUPSEPERATORBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTGROUPTOOLBARBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("STARTGROUPTOOLBARBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELLOGOFFBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELLOGOFFBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELLOGOFFBUTTONSBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELLOGOFFBUTTONSBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELLOGOFFBUTTONSHOTBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELLOGOFFBUTTONSHOTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELMFUBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELMFUBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELMOREPROGARROWBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELMOREPROGARROWBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELMOREPROGARROWHOTBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELMOREPROGARROWHOTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELMOREPROGBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELMOREPROGBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPANELPLACESBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPANELPLACESBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPLACESSEPARATORBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPLACESSEPARATORBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTPROGRAMSSEPARATORBmp {
            get {
                object obj = ResourceManager.GetObject("STARTPROGRAMSSEPARATORBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STARTUSERPANELBmp {
            get {
                object obj = ResourceManager.GetObject("STARTUSERPANELBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STATUSBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("STATUSBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STATUSPANEBmp {
            get {
                object obj = ResourceManager.GetObject("STATUSPANEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tabbackground133Bmp {
            get {
                object obj = ResourceManager.GetObject("Tabbackground133Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("TABBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMBOTHBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMBOTHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMLEFTBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMLEFTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMRIGHTBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMRIGHTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabItemTop {
            get {
                object obj = ResourceManager.GetObject("TabItemTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMTOPBOTHBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMTOPBOTHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMTOPLEFTBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMTOPLEFTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TABITEMTOPRIGHTBmp {
            get {
                object obj = ResourceManager.GetObject("TABITEMTOPRIGHTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TabPaneEdge {
            get {
                object obj = ResourceManager.GetObject("TabPaneEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDBUTTONNOEDGEBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDBUTTONNOEDGEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDBUTTONNOEDGEVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDBUTTONNOEDGEVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDBUTTONVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDBUTTONVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDFLASHBUTTONBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDFLASHBUTTONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDFLASHBUTTONGROUPMENUBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDFLASHBUTTONGROUPMENUBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDHOVERBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDHOVERBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLARROWGLYPHSBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLARROWGLYPHSBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLARROWSBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLARROWSBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLSHAFTHORIZONTALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLSHAFTHORIZONTALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLSHAFTVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLSHAFTVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLTHUMBGRIPPERHORIZONTALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLTHUMBGRIPPERHORIZONTALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLTHUMBGRIPPERVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLTHUMBGRIPPERVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLTHUMBHORIZONTALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLTHUMBHORIZONTALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBANDSCROLLTHUMBVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBANDSCROLLTHUMBVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARBACKGROUNDVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARBACKGROUNDVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARCHEVRONBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARCHEVRONBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARCHEVRONVERTBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARCHEVRONVERTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARGRIPPERBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARGRIPPERBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARGRIPPERVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARGRIPPERVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARSIZINGBARBOTTOMBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARSIZINGBARBOTTOMBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARSIZINGBARLEFTBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARSIZINGBARLEFTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARSIZINGBARRIGHTBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARSIZINGBARRIGHTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARSIZINGBARTOPBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARSIZINGBARTOPBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARTRAYBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARTRAYBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TASKBARTRAYVERTICALBmp {
            get {
                object obj = ResourceManager.GetObject("TASKBARTRAYVERTICALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToolBarBackground {
            get {
                object obj = ResourceManager.GetObject("ToolBarBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOOLBARBUTTONSBmp {
            get {
                object obj = ResourceManager.GetObject("TOOLBARBUTTONSBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToolBarButtonsSplit {
            get {
                object obj = ResourceManager.GetObject("ToolBarButtonsSplit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOOLBARBUTTONSSPLITDROPDOWNBmp {
            get {
                object obj = ResourceManager.GetObject("TOOLBARBUTTONSSPLITDROPDOWNBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOOLBARBUTTONSSPLITDROPDOWNGLYPHBmp {
            get {
                object obj = ResourceManager.GetObject("TOOLBARBUTTONSSPLITDROPDOWNGLYPHBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOOLBARGRIPPERBmp {
            get {
                object obj = ResourceManager.GetObject("TOOLBARGRIPPERBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOOLBARGRIPPERVERTBmp {
            get {
                object obj = ResourceManager.GetObject("TOOLBARGRIPPERVERTBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbardown13Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbardown13Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbardown16Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbardown16Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbardown25Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbardown25Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrackBarHorizontal {
            get {
                object obj = ResourceManager.GetObject("TrackBarHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarleft13Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarleft13Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarleft16Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarleft16Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarleft25Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarleft25Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarright13Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarright13Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarright16Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarright16Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarright25Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarright25Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarup13Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarup13Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarup16Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarup16Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Trackbarup25Bmp {
            get {
                object obj = ResourceManager.GetObject("Trackbarup25Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrackBarVertical {
            get {
                object obj = ResourceManager.GetObject("TrackBarVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TRAYCHEVRONHORIZONTALBmp {
            get {
                object obj = ResourceManager.GetObject("TRAYCHEVRONHORIZONTALBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TRAYCHEVRONHORIZONTALOPENBmp {
            get {
                object obj = ResourceManager.GetObject("TRAYCHEVRONHORIZONTALOPENBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Treeexpandcollapse10Bmp {
            get {
                object obj = ResourceManager.GetObject("Treeexpandcollapse10Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Treeexpandcollapse15Bmp {
            get {
                object obj = ResourceManager.GetObject("Treeexpandcollapse15Bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TREEEXPANDCOLLAPSEBmp {
            get {
                object obj = ResourceManager.GetObject("TREEEXPANDCOLLAPSEBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap USERTILEBACKGROUNDBmp {
            get {
                object obj = ResourceManager.GetObject("USERTILEBACKGROUNDBmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
