var _krypton_task_dialog_element_progres_bar_8_properties_8cs =
[
    [ "Krypton.Toolkit.KryptonTaskDialogElementProgresBarProperties", "class_krypton_1_1_toolkit_1_1_krypton_task_dialog_element_progres_bar_properties.html", "class_krypton_1_1_toolkit_1_1_krypton_task_dialog_element_progres_bar_properties" ]
];