var annotated_dup =
[
    [ "Krypton", "namespace_krypton.html", [
      [ "Docking", "namespace_krypton_1_1_docking.html", [
        [ "AutoHiddenGroupEventArgs", "class_krypton_1_1_docking_1_1_auto_hidden_group_event_args.html", "class_krypton_1_1_docking_1_1_auto_hidden_group_event_args" ],
        [ "AutoHiddenGroupPanelEventArgs", "class_krypton_1_1_docking_1_1_auto_hidden_group_panel_event_args.html", "class_krypton_1_1_docking_1_1_auto_hidden_group_panel_event_args" ],
        [ "AutoHiddenSeparatorResizeEventArgs", "class_krypton_1_1_docking_1_1_auto_hidden_separator_resize_event_args.html", "class_krypton_1_1_docking_1_1_auto_hidden_separator_resize_event_args" ],
        [ "AutoHiddenShowingStateEventArgs", "class_krypton_1_1_docking_1_1_auto_hidden_showing_state_event_args.html", "class_krypton_1_1_docking_1_1_auto_hidden_showing_state_event_args" ],
        [ "CancelDropDownEventArgs", "class_krypton_1_1_docking_1_1_cancel_drop_down_event_args.html", "class_krypton_1_1_docking_1_1_cancel_drop_down_event_args" ],
        [ "CancelUniqueNameEventArgs", "class_krypton_1_1_docking_1_1_cancel_unique_name_event_args.html", "class_krypton_1_1_docking_1_1_cancel_unique_name_event_args" ],
        [ "CloseRequestEventArgs", "class_krypton_1_1_docking_1_1_close_request_event_args.html", "class_krypton_1_1_docking_1_1_close_request_event_args" ],
        [ "ContextPageEventArgs", "class_krypton_1_1_docking_1_1_context_page_event_args.html", "class_krypton_1_1_docking_1_1_context_page_event_args" ],
        [ "DockableNavigatorEventArgs", "class_krypton_1_1_docking_1_1_dockable_navigator_event_args.html", "class_krypton_1_1_docking_1_1_dockable_navigator_event_args" ],
        [ "DockableWorkspaceCellEventArgs", "class_krypton_1_1_docking_1_1_dockable_workspace_cell_event_args.html", "class_krypton_1_1_docking_1_1_dockable_workspace_cell_event_args" ],
        [ "DockableWorkspaceEventArgs", "class_krypton_1_1_docking_1_1_dockable_workspace_event_args.html", "class_krypton_1_1_docking_1_1_dockable_workspace_event_args" ],
        [ "DockGlobalLoadingEventArgs", "class_krypton_1_1_docking_1_1_dock_global_loading_event_args.html", "class_krypton_1_1_docking_1_1_dock_global_loading_event_args" ],
        [ "DockGlobalSavingEventArgs", "class_krypton_1_1_docking_1_1_dock_global_saving_event_args.html", "class_krypton_1_1_docking_1_1_dock_global_saving_event_args" ],
        [ "DockingDragManager", "class_krypton_1_1_docking_1_1_docking_drag_manager.html", "class_krypton_1_1_docking_1_1_docking_drag_manager" ],
        [ "DockingDragTargetProvider", "class_krypton_1_1_docking_1_1_docking_drag_target_provider.html", "class_krypton_1_1_docking_1_1_docking_drag_target_provider" ],
        [ "DockingElement", "class_krypton_1_1_docking_1_1_docking_element.html", "class_krypton_1_1_docking_1_1_docking_element" ],
        [ "DockingElementClosedCollection", "class_krypton_1_1_docking_1_1_docking_element_closed_collection.html", "class_krypton_1_1_docking_1_1_docking_element_closed_collection" ],
        [ "DockingElementOpenCollection", "class_krypton_1_1_docking_1_1_docking_element_open_collection.html", "class_krypton_1_1_docking_1_1_docking_element_open_collection" ],
        [ "DockingManagerStrings", "class_krypton_1_1_docking_1_1_docking_manager_strings.html", "class_krypton_1_1_docking_1_1_docking_manager_strings" ],
        [ "DockingMultiUpdate", "class_krypton_1_1_docking_1_1_docking_multi_update.html", "class_krypton_1_1_docking_1_1_docking_multi_update" ],
        [ "DockPageLoadingEventArgs", "class_krypton_1_1_docking_1_1_dock_page_loading_event_args.html", "class_krypton_1_1_docking_1_1_dock_page_loading_event_args" ],
        [ "DockPageSavingEventArgs", "class_krypton_1_1_docking_1_1_dock_page_saving_event_args.html", "class_krypton_1_1_docking_1_1_dock_page_saving_event_args" ],
        [ "DockspaceCellEventArgs", "class_krypton_1_1_docking_1_1_dockspace_cell_event_args.html", "class_krypton_1_1_docking_1_1_dockspace_cell_event_args" ],
        [ "DockspaceEventArgs", "class_krypton_1_1_docking_1_1_dockspace_event_args.html", "class_krypton_1_1_docking_1_1_dockspace_event_args" ],
        [ "DockspaceSeparatorEventArgs", "class_krypton_1_1_docking_1_1_dockspace_separator_event_args.html", "class_krypton_1_1_docking_1_1_dockspace_separator_event_args" ],
        [ "DockspaceSeparatorResizeEventArgs", "class_krypton_1_1_docking_1_1_dockspace_separator_resize_event_args.html", "class_krypton_1_1_docking_1_1_dockspace_separator_resize_event_args" ],
        [ "DragTargetControlEdge", "class_krypton_1_1_docking_1_1_drag_target_control_edge.html", "class_krypton_1_1_docking_1_1_drag_target_control_edge" ],
        [ "DragTargetNull", "class_krypton_1_1_docking_1_1_drag_target_null.html", "class_krypton_1_1_docking_1_1_drag_target_null" ],
        [ "FloatingWindowEventArgs", "class_krypton_1_1_docking_1_1_floating_window_event_args.html", "class_krypton_1_1_docking_1_1_floating_window_event_args" ],
        [ "FloatspaceCellEventArgs", "class_krypton_1_1_docking_1_1_floatspace_cell_event_args.html", "class_krypton_1_1_docking_1_1_floatspace_cell_event_args" ],
        [ "FloatspaceEventArgs", "class_krypton_1_1_docking_1_1_floatspace_event_args.html", "class_krypton_1_1_docking_1_1_floatspace_event_args" ],
        [ "IDockingElement", "interface_krypton_1_1_docking_1_1_i_docking_element.html", "interface_krypton_1_1_docking_1_1_i_docking_element" ],
        [ "IFloatingMessages", "interface_krypton_1_1_docking_1_1_i_floating_messages.html", "interface_krypton_1_1_docking_1_1_i_floating_messages" ],
        [ "KryptonAutoHiddenGroup", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_group.html", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_group" ],
        [ "KryptonAutoHiddenPanel", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_panel.html", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_panel" ],
        [ "KryptonAutoHiddenProxyPage", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_proxy_page.html", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_proxy_page" ],
        [ "KryptonAutoHiddenSlidePanel", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_slide_panel.html", "class_krypton_1_1_docking_1_1_krypton_auto_hidden_slide_panel" ],
        [ "KryptonDockableNavigator", "class_krypton_1_1_docking_1_1_krypton_dockable_navigator.html", "class_krypton_1_1_docking_1_1_krypton_dockable_navigator" ],
        [ "KryptonDockableWorkspace", "class_krypton_1_1_docking_1_1_krypton_dockable_workspace.html", "class_krypton_1_1_docking_1_1_krypton_dockable_workspace" ],
        [ "KryptonDockingAutoHiddenGroup", "class_krypton_1_1_docking_1_1_krypton_docking_auto_hidden_group.html", "class_krypton_1_1_docking_1_1_krypton_docking_auto_hidden_group" ],
        [ "KryptonDockingControl", "class_krypton_1_1_docking_1_1_krypton_docking_control.html", "class_krypton_1_1_docking_1_1_krypton_docking_control" ],
        [ "KryptonDockingDockspace", "class_krypton_1_1_docking_1_1_krypton_docking_dockspace.html", "class_krypton_1_1_docking_1_1_krypton_docking_dockspace" ],
        [ "KryptonDockingEdge", "class_krypton_1_1_docking_1_1_krypton_docking_edge.html", "class_krypton_1_1_docking_1_1_krypton_docking_edge" ],
        [ "KryptonDockingEdgeAutoHidden", "class_krypton_1_1_docking_1_1_krypton_docking_edge_auto_hidden.html", "class_krypton_1_1_docking_1_1_krypton_docking_edge_auto_hidden" ],
        [ "KryptonDockingEdgeDocked", "class_krypton_1_1_docking_1_1_krypton_docking_edge_docked.html", "class_krypton_1_1_docking_1_1_krypton_docking_edge_docked" ],
        [ "KryptonDockingFloating", "class_krypton_1_1_docking_1_1_krypton_docking_floating.html", "class_krypton_1_1_docking_1_1_krypton_docking_floating" ],
        [ "KryptonDockingFloatingWindow", "class_krypton_1_1_docking_1_1_krypton_docking_floating_window.html", "class_krypton_1_1_docking_1_1_krypton_docking_floating_window" ],
        [ "KryptonDockingFloatspace", "class_krypton_1_1_docking_1_1_krypton_docking_floatspace.html", "class_krypton_1_1_docking_1_1_krypton_docking_floatspace" ],
        [ "KryptonDockingManager", "class_krypton_1_1_docking_1_1_krypton_docking_manager.html", "class_krypton_1_1_docking_1_1_krypton_docking_manager" ],
        [ "KryptonDockingNavigator", "class_krypton_1_1_docking_1_1_krypton_docking_navigator.html", "class_krypton_1_1_docking_1_1_krypton_docking_navigator" ],
        [ "KryptonDockingSpace", "class_krypton_1_1_docking_1_1_krypton_docking_space.html", "class_krypton_1_1_docking_1_1_krypton_docking_space" ],
        [ "KryptonDockingWorkspace", "class_krypton_1_1_docking_1_1_krypton_docking_workspace.html", "class_krypton_1_1_docking_1_1_krypton_docking_workspace" ],
        [ "KryptonDockspace", "class_krypton_1_1_docking_1_1_krypton_dockspace.html", "class_krypton_1_1_docking_1_1_krypton_dockspace" ],
        [ "KryptonDockspaceSeparator", "class_krypton_1_1_docking_1_1_krypton_dockspace_separator.html", "class_krypton_1_1_docking_1_1_krypton_dockspace_separator" ],
        [ "KryptonDockspaceSlide", "class_krypton_1_1_docking_1_1_krypton_dockspace_slide.html", "class_krypton_1_1_docking_1_1_krypton_dockspace_slide" ],
        [ "KryptonFloatingWindow", "class_krypton_1_1_docking_1_1_krypton_floating_window.html", "class_krypton_1_1_docking_1_1_krypton_floating_window" ],
        [ "KryptonFloatspace", "class_krypton_1_1_docking_1_1_krypton_floatspace.html", "class_krypton_1_1_docking_1_1_krypton_floatspace" ],
        [ "KryptonSpace", "class_krypton_1_1_docking_1_1_krypton_space.html", "class_krypton_1_1_docking_1_1_krypton_space" ],
        [ "KryptonStorePage", "class_krypton_1_1_docking_1_1_krypton_store_page.html", "class_krypton_1_1_docking_1_1_krypton_store_page" ],
        [ "PagesEventArgs", "class_krypton_1_1_docking_1_1_pages_event_args.html", "class_krypton_1_1_docking_1_1_pages_event_args" ],
        [ "ScreenAndOffsetEventArgs", "class_krypton_1_1_docking_1_1_screen_and_offset_event_args.html", "class_krypton_1_1_docking_1_1_screen_and_offset_event_args" ],
        [ "StorePageEventArgs", "class_krypton_1_1_docking_1_1_store_page_event_args.html", "class_krypton_1_1_docking_1_1_store_page_event_args" ],
        [ "UniqueNameEventArgs", "class_krypton_1_1_docking_1_1_unique_name_event_args.html", "class_krypton_1_1_docking_1_1_unique_name_event_args" ],
        [ "UniqueNamesEventArgs", "class_krypton_1_1_docking_1_1_unique_names_event_args.html", "class_krypton_1_1_docking_1_1_unique_names_event_args" ]
      ] ]
    ] ]
];