var dir_09e1ce1566417b63ccf988b16c589823 =
[
    [ "AutoHiddenGroupEventArgs.cs", "_auto_hidden_group_event_args_8cs.html", "_auto_hidden_group_event_args_8cs" ],
    [ "AutoHiddenGroupPanelEventArgs.cs", "_auto_hidden_group_panel_event_args_8cs.html", "_auto_hidden_group_panel_event_args_8cs" ],
    [ "AutoHiddenSeparatorResizeEventArgs.cs", "_auto_hidden_separator_resize_event_args_8cs.html", "_auto_hidden_separator_resize_event_args_8cs" ],
    [ "AutoHiddenShowingStateEventArgs.cs", "_auto_hidden_showing_state_event_args_8cs.html", "_auto_hidden_showing_state_event_args_8cs" ],
    [ "CancelDropDownEventArgs.cs", "_cancel_drop_down_event_args_8cs.html", "_cancel_drop_down_event_args_8cs" ],
    [ "CancelUniqueNameEventArgs.cs", "_cancel_unique_name_event_args_8cs.html", "_cancel_unique_name_event_args_8cs" ],
    [ "CloseRequestEventArgs.cs", "_close_request_event_args_8cs.html", "_close_request_event_args_8cs" ],
    [ "ContextPageEventArgs.cs", "_context_page_event_args_8cs.html", "_context_page_event_args_8cs" ],
    [ "DockableNavigatorEventArgs.cs", "_dockable_navigator_event_args_8cs.html", "_dockable_navigator_event_args_8cs" ],
    [ "DockableWorkspaceCellEventArgs.cs", "_dockable_workspace_cell_event_args_8cs.html", "_dockable_workspace_cell_event_args_8cs" ],
    [ "DockableWorkspaceEventArgs.cs", "_dockable_workspace_event_args_8cs.html", "_dockable_workspace_event_args_8cs" ],
    [ "DockGlobalLoadingEventArgs.cs", "_dock_global_loading_event_args_8cs.html", "_dock_global_loading_event_args_8cs" ],
    [ "DockGlobalSavingEventArgs.cs", "_dock_global_saving_event_args_8cs.html", "_dock_global_saving_event_args_8cs" ],
    [ "DockPageLoadingEventArgs.cs", "_dock_page_loading_event_args_8cs.html", "_dock_page_loading_event_args_8cs" ],
    [ "DockPageSavingEventArgs.cs", "_dock_page_saving_event_args_8cs.html", "_dock_page_saving_event_args_8cs" ],
    [ "DockspaceCellEventArgs.cs", "_dockspace_cell_event_args_8cs.html", "_dockspace_cell_event_args_8cs" ],
    [ "DockspaceEventArgs.cs", "_dockspace_event_args_8cs.html", "_dockspace_event_args_8cs" ],
    [ "DockspaceSeparatorEventArgs.cs", "_dockspace_separator_event_args_8cs.html", "_dockspace_separator_event_args_8cs" ],
    [ "DockspaceSeparatorResizeEventArgs.cs", "_dockspace_separator_resize_event_args_8cs.html", "_dockspace_separator_resize_event_args_8cs" ],
    [ "FloatingWindowEventArgs.cs", "_floating_window_event_args_8cs.html", "_floating_window_event_args_8cs" ],
    [ "FloatspaceCellEventArgs.cs", "_floatspace_cell_event_args_8cs.html", "_floatspace_cell_event_args_8cs" ],
    [ "FloatspaceEventArgs.cs", "_floatspace_event_args_8cs.html", "_floatspace_event_args_8cs" ],
    [ "PagesEventArgs.cs", "_pages_event_args_8cs.html", "_pages_event_args_8cs" ],
    [ "ScreenAndOffsetEventArgs.cs", "_screen_and_offset_event_args_8cs.html", "_screen_and_offset_event_args_8cs" ],
    [ "StorePageEventArgs.cs", "_store_page_event_args_8cs.html", "_store_page_event_args_8cs" ],
    [ "UniqueNameEventArgs.cs", "_unique_name_event_args_8cs.html", "_unique_name_event_args_8cs" ],
    [ "UniqueNamesEventArgs.cs", "_unique_names_event_args_8cs.html", "_unique_names_event_args_8cs" ]
];