# Generates placeholder image accessors that match Krypton.Resources designer types.
param(
    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$resourceRoot = Split-Path $PSScriptRoot -Parent
$designers = Get-ChildItem -LiteralPath (Join-Path $resourceRoot 'ResourceFiles') -Recurse -Filter '*.Designer.cs'
$skip = @(
    'OutlookGridStringResources.Designer.cs',
    'PaletteSchemaResources.Designer.cs',
    'CursorResources.Designer.cs'
)

function ConvertTo-ResourcePropertyName {
    param([string]$Name)

    # ResXFileCodeGenerator replaces characters that are not valid in an identifier, including '.'.
    $builder = New-Object System.Text.StringBuilder
    foreach ($char in $Name.ToCharArray()) {
        if ([char]::IsLetterOrDigit($char) -or $char -eq '_') {
            [void]$builder.Append($char)
        }
        else {
            [void]$builder.Append('_')
        }
    }

    $result = $builder.ToString()
    if ($result.Length -gt 0 -and [char]::IsDigit($result[0])) {
        $result = '_' + $result
    }

    return $result
}

function Get-ResourceImageSizes {
    $sizes = @{}
    $resxFiles = @(Get-ChildItem -LiteralPath (Join-Path $resourceRoot 'ResourceFiles') -Recurse -Filter '*.resx' | Sort-Object FullName)
    $cacheDirectory = Join-Path $PSScriptRoot 'obj'
    $cachePath = Join-Path $cacheDirectory 'image-sizes.txt'
    $cacheKeyBuilder = New-Object System.Text.StringBuilder
    [void]$cacheKeyBuilder.AppendLine('v2')
    foreach ($resx in $resxFiles) {
        [void]$cacheKeyBuilder.Append($resx.FullName)
        [void]$cacheKeyBuilder.Append('|')
        [void]$cacheKeyBuilder.Append($resx.Length)
        [void]$cacheKeyBuilder.Append('|')
        [void]$cacheKeyBuilder.Append($resx.LastWriteTimeUtc.Ticks)
        [void]$cacheKeyBuilder.AppendLine()
    }

    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($cacheKeyBuilder.ToString()))
    }
    finally {
        $sha.Dispose()
    }

    $cacheKey = [System.BitConverter]::ToString($hashBytes).Replace('-', '')
    if (Test-Path -LiteralPath $cachePath) {
        $cached = [System.IO.File]::ReadAllLines($cachePath)
        if ($cached.Length -gt 0 -and $cached[0] -eq $cacheKey) {
            foreach ($line in $cached | Select-Object -Skip 1) {
                $pair = $line.Split('=', 2)
                if ($pair.Length -eq 2) {
                    $sizes[$pair[0]] = $pair[1]
                }
            }

            return $sizes
        }
    }

    Add-Type -AssemblyName System.Drawing
    Add-Type -AssemblyName System.Windows.Forms
    foreach ($resx in $resxFiles) {
        $className = [System.IO.Path]::GetFileNameWithoutExtension($resx.Name)
        $designerPath = Join-Path $resx.DirectoryName ($className + '.Designer.cs')
        if (-not (Test-Path -LiteralPath $designerPath)) {
            continue
        }

        $designerText = [System.IO.File]::ReadAllText($designerPath)
        $namespaceMatch = [regex]::Match($designerText, 'namespace ([^\s\{]+)')
        if (-not $namespaceMatch.Success) {
            continue
        }

        $namespaceName = $namespaceMatch.Groups[1].Value
        $reader = New-Object System.Resources.ResXResourceReader($resx.FullName)
        $reader.BasePath = $resx.DirectoryName
        try {
            foreach ($entry in $reader) {
                $image = $entry.Value
                $isImage = $image -is [System.Drawing.Image] -or $image -is [System.Drawing.Icon]
                if (-not $isImage) {
                    continue
                }

                $width = [int]$image.Width
                $height = [int]$image.Height
                if ($image -is [System.IDisposable]) {
                    $image.Dispose()
                }

                if ($width -le 0) { $width = 16 }
                if ($height -le 0) { $height = 16 }
                $propertyName = ConvertTo-ResourcePropertyName $entry.Key
                $sizes["$namespaceName.$className.$propertyName"] = "$width,$height"
            }
        }
        finally {
            $reader.Close()
        }
    }

    New-Item -ItemType Directory -Path $cacheDirectory -Force | Out-Null
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add($cacheKey)
    foreach ($key in ($sizes.Keys | Sort-Object)) {
        $lines.Add("$key=$($sizes[$key])")
    }

    $utf8Bom = New-Object System.Text.UTF8Encoding $true
    [System.IO.File]::WriteAllLines($cachePath, $lines.ToArray(), $utf8Bom)
    return $sizes
}

$imageSizes = Get-ResourceImageSizes
$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine('// Generated by New-KryptonResourceFallback.ps1. Image getters return placeholders; string resources are compiled from their .resx.')
[void]$builder.AppendLine()

foreach ($file in $designers) {
    if ($skip -contains $file.Name) {
        continue
    }

    $text = [System.IO.File]::ReadAllText($file.FullName)
    $namespaceMatch = [regex]::Match($text, 'namespace ([^\s\{]+)')
    $classMatch = [regex]::Match($text, 'internal class (\w+)')
    if (-not $namespaceMatch.Success -or -not $classMatch.Success) {
        throw "Could not read resource type from $($file.FullName)"
    }

    [void]$builder.AppendLine("namespace $($namespaceMatch.Groups[1].Value)")
    [void]$builder.AppendLine('{')
    [void]$builder.AppendLine("    internal class $($classMatch.Groups[1].Value)")
    [void]$builder.AppendLine('    {')
    [void]$builder.AppendLine('        internal static System.Resources.ResourceManager ResourceManager => Krypton.Toolkit.ResourceFiles.KryptonResourceFallback.ResourceManager;')
    [void]$builder.AppendLine('        internal static System.Globalization.CultureInfo Culture')
    [void]$builder.AppendLine('        {')
    [void]$builder.AppendLine('            get => Krypton.Toolkit.ResourceFiles.KryptonResourceFallback.Culture;')
    [void]$builder.AppendLine('            set => Krypton.Toolkit.ResourceFiles.KryptonResourceFallback.Culture = value;')
    [void]$builder.AppendLine('        }')

    $properties = [regex]::Matches($text, 'internal static (.+?) ([A-Za-z_][A-Za-z0-9_]*) \{\r?\n')
    foreach ($property in $properties) {
        $typeName = $property.Groups[1].Value.Trim()
        $propertyName = $property.Groups[2].Value
        if ($propertyName -eq 'ResourceManager' -or $propertyName -eq 'Culture') {
            continue
        }

        $expression = $null
        $sizeKey = "$($namespaceMatch.Groups[1].Value).$($classMatch.Groups[1].Value).$propertyName"
        $size = $imageSizes[$sizeKey]
        $width = 16
        $height = 16
        if (-not [string]::IsNullOrWhiteSpace($size)) {
            $parts = $size.Split(',')
            $width = [int]$parts[0]
            $height = [int]$parts[1]
        }

        if ($typeName.EndsWith('Bitmap') -or $typeName.EndsWith('Icon')) {
            if ([string]::IsNullOrWhiteSpace($size)) {
                throw "No image size for $sizeKey. The matching .resx did not contain that image."
            }
        }

        if ($typeName.EndsWith('Bitmap')) {
            $expression = "Krypton.Toolkit.ResourceFiles.KryptonResourceFallback.BitmapOf($width, $height, `"$propertyName`")"
        }
        elseif ($typeName.EndsWith('Icon')) {
            $expression = "Krypton.Toolkit.ResourceFiles.KryptonResourceFallback.IconOf($width, $height, `"$propertyName`")"
        }
        elseif ($typeName.EndsWith('byte[]')) {
            $expression = 'Krypton.Toolkit.ResourceFiles.KryptonResourceFallback.PlaceholderBytes'
        }
        elseif ($typeName -eq 'string') {
            $expression = 'string.Empty'
        }
        else {
            throw "Unsupported resource property type '$typeName' on $($classMatch.Groups[1].Value).$propertyName"
        }

        [void]$builder.AppendLine("        internal static $typeName $propertyName => $expression;")
    }

    [void]$builder.AppendLine('    }')
    [void]$builder.AppendLine('}')
    [void]$builder.AppendLine()
}

$content = $builder.ToString()
$directory = Split-Path $OutputPath -Parent
if (-not [string]::IsNullOrEmpty($directory)) {
    New-Item -ItemType Directory -Path $directory -Force | Out-Null
}

$utf8Bom = New-Object System.Text.UTF8Encoding $true
if (Test-Path -LiteralPath $OutputPath) {
    $existing = [System.IO.File]::ReadAllText($OutputPath)
    if ($existing -eq $content) {
        return
    }
}

[System.IO.File]::WriteAllText($OutputPath, $content, $utf8Bom)
