#region BSD License
/*
 *
 *  New BSD 3-Clause License (https://github.com/Krypton-Suite/Standard-Toolkit/blob/master/LICENSE)
 *  Modifications by Peter Wagner (aka Wagnerp), Simon Coghlan (aka Smurf-IV), Giduac, Ahmed Abdelhameed, tobitege et al. 2025 - 2025. All rights reserved.
 *
 */
#endregion

namespace Krypton.Toolkit;

public sealed class PaletteSparkleBlueDarkMode_BaseScheme : KryptonColorSchemeBase
{
    public override Color TextLabelControl                 { get; set; } = Color.White;
    public override Color TextButtonNormal                 { get; set; } = Color.FromArgb( 70, 70, 70);
    public override Color TextButtonChecked                { get; set; } = Color.Black;
    public override Color ButtonNormalBorder               { get; set; } = Color.FromArgb(137, 135, 133);
    public override Color ButtonNormalDefaultBorder        { get; set; } = Color.FromArgb(127, 125, 123);
    public override Color ButtonNormalBack1                { get; set; } = Color.FromArgb(203, 213, 223);
    public override Color ButtonNormalBack2                { get; set; } = Color.FromArgb(255, 255, 255);
    public override Color ButtonNormalDefaultBack1         { get; set; } = Color.FromArgb(187, 192, 198);
    public override Color ButtonNormalDefaultBack2         { get; set; } = Color.FromArgb(224, 227, 231);
    public override Color ButtonNormalNavigatorBack1       { get; set; } = Color.FromArgb(204, 208, 214);
    public override Color ButtonNormalNavigatorBack2       { get; set; } = Color.FromArgb(229, 232, 236);
    public override Color PanelClient                      { get; set; } = Color.FromArgb( 83, 83, 83);
    public override Color PanelAlternative                 { get; set; } = Color.FromArgb( 70, 70, 70);
    public override Color ControlBorder                    { get; set; } = Color.FromArgb( 30, 30, 30);
    public override Color SeparatorHighBorder1             { get; set; } = Color.FromArgb(167, 167, 167);
    public override Color SeparatorHighBorder2             { get; set; } = Color.FromArgb(119, 119, 119);
    public override Color HeaderPrimaryBack1               { get; set; } = Color.FromArgb(240, 241, 242);
    public override Color HeaderPrimaryBack2               { get; set; } = Color.FromArgb(189, 193, 200);
    public override Color HeaderSecondaryBack1             { get; set; } = Color.FromArgb(221, 224, 227);
    public override Color HeaderSecondaryBack2             { get; set; } = Color.FromArgb(221, 224, 227);
    public override Color HeaderText                       { get; set; } = Color.Black;
    public override Color StatusStripText                  { get; set; } = Color.White;
    public override Color ButtonBorder                     { get; set; } = Color.FromArgb(155, 163, 167);
    public override Color SeparatorLight                   { get; set; } = Color.FromArgb(200, 200, 200);
    public override Color SeparatorDark                    { get; set; } = Color.FromArgb(86, 94, 118);
    public override Color GripLight                        { get; set; } = Color.FromArgb(190, 190, 190);
    public override Color GripDark                         { get; set; } = Color.Black;
    public override Color ToolStripBack                    { get; set; } = Color.FromArgb(99, 108, 135);
    public override Color StatusStripLight                 { get; set; } = Color.FromArgb(99, 108, 135);
    public override Color StatusStripDark                  { get; set; } = Color.Black;
    public override Color ImageMargin                      { get; set; } = Color.FromArgb(240, 240, 240);
    public override Color ToolStripBegin                   { get; set; } = Color.FromArgb(200, 200, 200);
    public override Color ToolStripMiddle                  { get; set; } = Color.FromArgb(99, 108, 135);
    public override Color ToolStripEnd                     { get; set; } = Color.FromArgb(72, 81, 102);
    public override Color OverflowBegin                    { get; set; } = Color.FromArgb(72, 81, 102);
    public override Color OverflowMiddle                   { get; set; } = Color.FromArgb(72, 81, 102);
    public override Color OverflowEnd                      { get; set; } = Color.FromArgb( 30, 30, 30);
    public override Color ToolStripBorder                  { get; set; } = Color.FromArgb( 30, 30, 30);
    public override Color FormBorderActive                 { get; set; } = Color.FromArgb( 47, 47, 47);
    public override Color FormBorderInactive               { get; set; } = Color.FromArgb(146, 146, 146);
    public override Color FormBorderActiveLight            { get; set; } = Color.FromArgb( 77, 77, 77);
    public override Color FormBorderActiveDark             { get; set; } = Color.FromArgb(102, 102, 102);
    public override Color FormBorderInactiveLight          { get; set; } = Color.FromArgb(153, 153, 153);
    public override Color FormBorderInactiveDark           { get; set; } = Color.FromArgb(171, 171, 171);
    public override Color FormBorderHeaderActive           { get; set; } = Color.FromArgb( 65, 65, 65);
    public override Color FormBorderHeaderInactive         { get; set; } = Color.FromArgb(154, 154, 154);
    public override Color FormBorderHeaderActive1          { get; set; } = Color.FromArgb( 42, 43, 43);
    public override Color FormBorderHeaderActive2          { get; set; } = Color.FromArgb( 74, 74, 74);
    public override Color FormBorderHeaderInactive1        { get; set; } = Color.FromArgb(146, 146, 146);
    public override Color FormBorderHeaderInactive2        { get; set; } = Color.FromArgb(158, 158, 158);
    public override Color FormHeaderShortActive            { get; set; } = Color.FromArgb(174, 209, 255);
    public override Color FormHeaderShortInactive          { get; set; } = Color.FromArgb(225, 225, 225);
    public override Color FormHeaderLongActive             { get; set; } = Color.FromArgb(255, 255, 255);
    public override Color FormHeaderLongInactive           { get; set; } = Color.FromArgb(225, 225, 225);
    public override Color FormButtonBorderTrack            { get; set; } = Color.FromArgb( 88, 95, 104);
    public override Color FormButtonBack1Track             { get; set; } = Color.FromArgb( 91, 105, 123);
    public override Color FormButtonBack2Track             { get; set; } = Color.FromArgb(173, 199, 214);
    public override Color FormButtonBorderPressed          { get; set; } = Color.FromArgb( 18, 18, 18);
    public override Color FormButtonBack1Pressed           { get; set; } = Color.FromArgb( 0, 0, 0);
    public override Color FormButtonBack2Pressed           { get; set; } = Color.FromArgb( 65, 83, 102);
    public override Color TextButtonFormNormal             { get; set; } = Color.FromArgb( 70, 70, 70);
    public override Color TextButtonFormTracking           { get; set; } = Color.FromArgb(255, 255, 255);
    public override Color TextButtonFormPressed            { get; set; } = Color.FromArgb(255, 255, 255);
    public override Color LinkNotVisitedOverrideControl    { get; set; } = Color.Blue;
    public override Color LinkVisitedOverrideControl       { get; set; } = Color.Purple;
    public override Color LinkPressedOverrideControl       { get; set; } = Color.Red;
    public override Color LinkNotVisitedOverridePanel      { get; set; } = Color.FromArgb(180, 210, 255);
    public override Color LinkVisitedOverridePanel         { get; set; } = Color.Violet;
    public override Color LinkPressedOverridePanel         { get; set; } = Color.FromArgb(255, 90, 90);
    public override Color TextLabelPanel                   { get; set; } = Color.White;
    public override Color RibbonTabTextNormal              { get; set; } = Color.White;
    public override Color RibbonTabTextChecked             { get; set; } = Color.Black;
    public override Color RibbonTabSelected1               { get; set; } = Color.Black;
    public override Color RibbonTabSelected2               { get; set; } = Color.Silver;
    public override Color RibbonTabSelected3               { get; set; } = Color.FromArgb(177, 177, 188);
    public override Color RibbonTabSelected4               { get; set; } = Color.FromArgb(167, 167, 178);
    public override Color RibbonTabSelected5               { get; set; } = Color.FromArgb(137, 137, 148);
    public override Color RibbonTabTracking1               { get; set; } = Color.FromArgb(159, 156, 150);
    public override Color RibbonTabTracking2               { get; set; } = Color.FromArgb(200, 200, 255);
    public override Color RibbonTabHighlight1              { get; set; } = Color.Black;
    public override Color RibbonTabHighlight2              { get; set; } = Color.FromArgb(107, 145, 238);
    public override Color RibbonTabHighlight3              { get; set; } = Color.FromArgb( 97, 135, 228);
    public override Color RibbonTabHighlight4              { get; set; } = Color.FromArgb( 82, 120, 213);
    public override Color RibbonTabHighlight5              { get; set; } = Color.FromArgb(137, 137, 148);
    public override Color RibbonTabSeparatorColor          { get; set; } = Color.Black;
    public override Color RibbonGroupsArea1                { get; set; } = Color.Black;
    public override Color RibbonGroupsArea2                { get; set; } = Color.Black;
    public override Color RibbonGroupsArea3                { get; set; } = Color.FromArgb( 96, 96, 110);
    public override Color RibbonGroupsArea4                { get; set; } = Color.FromArgb(140, 140, 150);
    public override Color RibbonGroupsArea5                { get; set; } = Color.FromArgb(140, 140, 150);
    public override Color RibbonGroupBorder1               { get; set; } = Color.Black;
    public override Color RibbonGroupBorder2               { get; set; } = Color.Black;
    public override Color RibbonGroupTitle1                { get; set; } = Color.DimGray;
    public override Color RibbonGroupTitle2                { get; set; } = Color.Black;
    public override Color RibbonGroupBorderContext1        { get; set; } = Color.Black;
    public override Color RibbonGroupBorderContext2        { get; set; } = Color.Black;
    public override Color RibbonGroupTitleContext1         { get; set; } = Color.DimGray;
    public override Color RibbonGroupTitleContext2         { get; set; } = Color.Black;
    public override Color RibbonGroupDialogDark            { get; set; } = Color.Black;
    public override Color RibbonGroupDialogLight           { get; set; } = Color.White;
    public override Color RibbonGroupTitleTracking1        { get; set; } = Color.FromArgb(120, 120, 120);
    public override Color RibbonGroupTitleTracking2        { get; set; } = Color.FromArgb(65, 65, 65);
    public override Color RibbonMinimizeBarDark            { get; set; } = Color.FromArgb(27, 31, 38);
    public override Color RibbonMinimizeBarLight           { get; set; } = Color.FromArgb(150, 150, 150);
    public override Color RibbonGroupCollapsedBorder1      { get; set; } = Color.Black;
    public override Color RibbonGroupCollapsedBorder2      { get; set; } = Color.Black;
    public override Color RibbonGroupCollapsedBorder3      { get; set; } = Color.FromArgb( 75, 78, 85);
    public override Color RibbonGroupCollapsedBorder4      { get; set; } = Color.FromArgb(129, 133, 145);
    public override Color RibbonGroupCollapsedBack1        { get; set; } = Color.FromArgb(167, 167, 168);
    public override Color RibbonGroupCollapsedBack2        { get; set; } = Color.FromArgb( 93, 93, 95);
    public override Color RibbonGroupCollapsedBack3        { get; set; } = Color.FromArgb( 20, 21, 23);
    public override Color RibbonGroupCollapsedBack4        { get; set; } = Color.FromArgb( 52, 60, 92);
    public override Color RibbonGroupCollapsedBorderT1     { get; set; } = Color.Black;
    public override Color RibbonGroupCollapsedBorderT2     { get; set; } = Color.Black;
    public override Color RibbonGroupCollapsedBorderT3     { get; set; } = Color.FromArgb( 48, 89, 146);
    public override Color RibbonGroupCollapsedBorderT4     { get; set; } = Color.FromArgb( 85, 132, 196);
    public override Color RibbonGroupCollapsedBackT1       { get; set; } = Color.FromArgb(166, 173, 182);
    public override Color RibbonGroupCollapsedBackT2       { get; set; } = Color.FromArgb( 92, 105, 121);
    public override Color RibbonGroupCollapsedBackT3       { get; set; } = Color.FromArgb( 19, 37, 61);
    public override Color RibbonGroupCollapsedBackT4       { get; set; } = Color.FromArgb( 56, 119, 191);
    public override Color RibbonGroupFrameBorder1          { get; set; } = Color.Black;
    public override Color RibbonGroupFrameBorder2          { get; set; } = Color.Gray;
    public override Color RibbonGroupFrameInside1          { get; set; } = Color.FromArgb(225, 225, 225);
    public override Color RibbonGroupFrameInside2          { get; set; } = Color.FromArgb(170, 170, 170);
    public override Color RibbonGroupFrameInside3          { get; set; } = Color.FromArgb(150, 150, 150);
    public override Color RibbonGroupFrameInside4          { get; set; } = Color.FromArgb(205, 205, 205);
    public override Color RibbonGroupCollapsedText         { get; set; } = Color.White;
    public override Color RibbonGroupButtonText            { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color AlternatePressedBack1            { get; set; } = Color.FromArgb(158, 163, 172);
    public override Color AlternatePressedBack2            { get; set; } = Color.FromArgb(212, 215, 216);
    public override Color AlternatePressedBorder1          { get; set; } = Color.FromArgb(124, 125, 125);
    public override Color AlternatePressedBorder2          { get; set; } = Color.FromArgb(186, 186, 186);
    public override Color FormButtonBack1Checked           { get; set; } = Color.FromArgb( 43, 55, 67);
    public override Color FormButtonBack2Checked           { get; set; } = Color.FromArgb(106, 122, 140);
    public override Color FormButtonBorderCheck            { get; set; } = Color.FromArgb( 18, 18, 18);
    public override Color FormButtonBack1CheckTrack        { get; set; } = Color.FromArgb( 33, 45, 57);
    public override Color FormButtonBack2CheckTrack        { get; set; } = Color.FromArgb(136, 152, 170);
    public override Color RibbonQATMini1                   { get; set; } = Color.FromArgb(20, 21, 23);
    public override Color RibbonQATMini2                   { get; set; } = Color.FromArgb(150, 150, 150);
    public override Color RibbonQATMini3                   { get; set; } = Color.FromArgb(45, 45, 45);
    public override Color RibbonQATMini4                   { get; set; } = Color.FromArgb(14, Color.White);
    public override Color RibbonQATMini5                   { get; set; } = Color.FromArgb(14, Color.White);
    public override Color RibbonQATMini1I                  { get; set; } = Color.Black;
    public override Color RibbonQATMini2I                  { get; set; } = Color.Black;
    public override Color RibbonQATMini3I                  { get; set; } = Color.Black;
    public override Color RibbonQATMini4I                  { get; set; } = Color.FromArgb(14, Color.White);
    public override Color RibbonQATMini5I                  { get; set; } = Color.FromArgb(14, Color.White);
    public override Color RibbonQATFullbar1                { get; set; } = Color.FromArgb(150, 150, 150);
    public override Color RibbonQATFullbar2                { get; set; } = Color.FromArgb(45, 45, 45);
    public override Color RibbonQATFullbar3                { get; set; } = Color.FromArgb(20, 21, 23);
    public override Color RibbonQATButtonDark              { get; set; } = Color.Black;
    public override Color RibbonQATButtonLight             { get; set; } = Color.White;
    public override Color RibbonQATOverflow1               { get; set; } = Color.FromArgb(240, 240, 240);
    public override Color RibbonQATOverflow2               { get; set; } = Color.Black;
    public override Color RibbonGroupSeparatorDark         { get; set; } = Color.Gray;
    public override Color RibbonGroupSeparatorLight        { get; set; } = Color.Black;
    public override Color ButtonClusterButtonBack1         { get; set; } = Color.FromArgb(210, 217, 219);
    public override Color ButtonClusterButtonBack2         { get; set; } = Color.FromArgb(214, 222, 223);
    public override Color ButtonClusterButtonBorder1       { get; set; } = Color.FromArgb(179, 188, 191);
    public override Color ButtonClusterButtonBorder2       { get; set; } = Color.FromArgb(145, 156, 159);
    public override Color NavigatorMiniBackColor           { get; set; } = Color.FromArgb(235, 235, 235);
    public override Color GridListNormal1                  { get; set; } = Color.White;
    public override Color GridListNormal2                  { get; set; } = Color.FromArgb(212, 215, 219);
    public override Color GridListPressed1                 { get; set; } = Color.FromArgb(210, 213, 218);
    public override Color GridListPressed2                 { get; set; } = Color.FromArgb(252, 253, 253);
    public override Color GridListSelected                 { get; set; } = Color.FromArgb(186, 189, 194);
    public override Color GridSheetColNormal1              { get; set; } = Color.FromArgb(248, 248, 248);
    public override Color GridSheetColNormal2              { get; set; } = Color.FromArgb(222, 222, 222);
    public override Color GridSheetColPressed1             { get; set; } = Color.FromArgb(224, 224, 224);
    public override Color GridSheetColPressed2             { get; set; } = Color.FromArgb(195, 195, 195);
    public override Color GridSheetColSelected1            { get; set; } = Color.FromArgb(249, 217, 159);
    public override Color GridSheetColSelected2            { get; set; } = Color.FromArgb(241, 193, 95);
    public override Color GridSheetRowNormal               { get; set; } = Color.FromArgb(237, 237, 237);
    public override Color GridSheetRowPressed              { get; set; } = Color.FromArgb(196, 196, 196);
    public override Color GridSheetRowSelected             { get; set; } = Color.FromArgb(255, 213, 141);
    public override Color GridDataCellBorder               { get; set; } = Color.FromArgb(188, 195, 209);
    public override Color GridDataCellSelected             { get; set; } = Color.FromArgb(194, 217, 240);
    public override Color InputControlTextNormal           { get; set; } = Color.White;
    public override Color InputControlTextDisabled         { get; set; } = Color.FromArgb(172, 168, 153);
    public override Color InputControlBorderNormal         { get; set; } = Color.FromArgb(137, 137, 137);
    public override Color InputControlBorderDisabled       { get; set; } = Color.FromArgb(204, 204, 204);
    public override Color InputControlBackNormal           { get; set; } = Color.FromArgb(70, 70, 70);
    public override Color InputControlBackDisabled         { get; set; } = SystemColors.Control;
    public override Color InputControlBackInactive         { get; set; } = Color.FromArgb(232, 232, 232);
    public override Color InputDropDownNormal1             { get; set; } = Color.FromArgb(124, 124, 124);
    public override Color InputDropDownNormal2             { get; set; } = Color.FromArgb(255, 248, 203);
    public override Color InputDropDownDisabled1           { get; set; } = Color.FromArgb(172, 168, 153);
    public override Color InputDropDownDisabled2           { get; set; } = Color.Transparent;
    public override Color ContextMenuHeadingBack           { get; set; } = Color.FromArgb(235, 235, 235);
    public override Color ContextMenuHeadingText           { get; set; } = Color.FromArgb( 76, 83, 92);
    public override Color ContextMenuImageColumn           { get; set; } = Color.FromArgb(239, 239, 239);
    public override Color AppButtonBack1                   { get; set; } = Color.FromArgb(109, 108, 108);
    public override Color AppButtonBack2                   { get; set; } = Color.FromArgb(104, 103, 103);
    public override Color AppButtonBorder                  { get; set; } = Color.Black;
    public override Color AppButtonOuter1                  { get; set; } = Color.FromArgb(20, 21, 23);
    public override Color AppButtonOuter2                  { get; set; } = Color.Black;
    public override Color AppButtonOuter3                  { get; set; } = Color.FromArgb(20, 21, 23);
    public override Color AppButtonInner1                  { get; set; } = Color.FromArgb(20, 21, 23);
    public override Color AppButtonInner2                  { get; set; } = Color.Black;
    public override Color AppButtonMenuDocsBack            { get; set; } = Color.FromArgb(237, 237, 242);
    public override Color AppButtonMenuDocsText            { get; set; } = Color.Black;
    public override Color SeparatorHighInternalBorder1     { get; set; } = Color.FromArgb(240, 241, 242);
    public override Color SeparatorHighInternalBorder2     { get; set; } = Color.FromArgb(195, 200, 206);
    public override Color RibbonGalleryBorder              { get; set; } = Color.Black;
    public override Color RibbonGalleryBackNormal          { get; set; } = Color.FromArgb(215, 215, 215);
    public override Color RibbonGalleryBackTracking        { get; set; } = Color.FromArgb(238, 238, 238);
    public override Color RibbonGalleryBack1               { get; set; } = Color.FromArgb(195, 200, 209);
    public override Color RibbonGalleryBack2               { get; set; } = Color.FromArgb(217, 220, 224);
    public override Color RibbonTabTracking3               { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color RibbonTabTracking4               { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color RibbonGroupBorder3               { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color RibbonGroupBorder4               { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color RibbonGroupBorder5               { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color RibbonGroupTitleText             { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color RibbonDropArrowLight             { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color RibbonDropArrowDark              { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color HeaderDockInactiveBack1          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color HeaderDockInactiveBack2          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorBorder            { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorText              { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorTrack1            { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorTrack2            { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorPressed1          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorPressed2          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorChecked1          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ButtonNavigatorChecked2          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color ToolTipBottom                    { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color MenuItemText                     { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color MenuMarginGradientStart          { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color MenuMarginGradientMiddle         { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color MenuMarginGradientEnd            { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color DisabledMenuItemText             { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color MenuStripText                    { get; set; } = GlobalStaticValues.EMPTY_COLOR;
    public override Color TrackBarTickMarks                { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color TrackBarTopTrack                 { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color TrackBarBottomTrack              { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color TrackBarFillTrack                { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color TrackBarOutsidePosition          { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
    public override Color TrackBarBorderPosition           { get; set; } = GlobalStaticValues.EMPTY_COLOR; // missing value
}
